### ISSUE TITLE
Утка не грузится

### ISSUE THREAD

**Issue by Shuttafaka** [PlutoSolutions/Pyro#2]
Пофикси утка не грузится даже на чистом майне

**Comment by mr-nv** [comment]
log

**Comment by Shuttafaka** [comment]
[crash-2022-06-25_09.46.08-client.txt](https://github.com/PlutoSolutions/Pyro/files/8984430/crash-2022-06-25_09.46.08-client.txt)

**Comment by mr-nv** [comment]
аааааааааа бля я понял куда тебе написать можно я тебе джарник скину затестишь

**Comment by Shuttafaka** [comment]
дс Shuttafaka_#6715 скинь протещю

**Comment by mr-nv** [comment]
fixed
